
# ==============================================================#=
# FILE:
#     project_config.yaml
#
# DESCRIPTION:
#     """""""""""""""""""""""""""""""""""""""""""""'
#     """""""""""""""""""""""""""""""""""""""""""""'
#     """""""""""""""""""""""""""""""""""""""""""""'
# ==============================================================#=

---
:repositories:

    - project:
        :git_url: git@github.com:raensink/ti.quickstart.project
        :local_dir: project

    - mcu_lib:
        :git_url: git@github.com:raensink/ti.quickstart.mculib

    - app:
        :git_url: git@github.com:raensink/ti.quickstart.app

